import { z } from 'zod';

/**
 * 統一錯誤回應格式（prompt.md §二「必須有統一錯誤回應格式」）。
 *
 * 所有非 2xx 回應一律為：
 * {
 *   "error": {
 *     "code": "VALIDATION_FAILED",
 *     "message": "人類可讀訊息",
 *     "details": [ { "path": "questions[0].options", "message": "至少需要兩個選項" } ],
 *     "requestId": "01J...",
 *     "timestamp": "2026-07-30T13:00:00.000Z"
 *   }
 * }
 *
 * message 與 details 都不得包含任何密鑰、連線字串或外部 API 原始回應。
 */

export const ERROR_CODES = {
  // --- 通用 (4xx) ---
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',

  // --- 通用 (5xx) ---
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',

  // --- 初始化 / 認證 ---
  SETUP_ALREADY_COMPLETED: 'SETUP_ALREADY_COMPLETED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // --- 題庫 ---
  SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
  CHAPTER_NOT_FOUND: 'CHAPTER_NOT_FOUND',
  CHAPTER_SUBJECT_MISMATCH: 'CHAPTER_SUBJECT_MISMATCH',
  QUESTION_GROUP_NOT_FOUND: 'QUESTION_GROUP_NOT_FOUND',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_IN_USE: 'QUESTION_IN_USE',

  // --- 匯入 ---
  IMPORT_BATCH_NOT_FOUND: 'IMPORT_BATCH_NOT_FOUND',
  IMPORT_BATCH_NOT_COMMITTABLE: 'IMPORT_BATCH_NOT_COMMITTABLE',
  IMPORT_HAS_BLOCKING_ERRORS: 'IMPORT_HAS_BLOCKING_ERRORS',
  IMPORT_FILE_INVALID_JSON: 'IMPORT_FILE_INVALID_JSON',
  IMPORT_TOO_MANY_QUESTIONS: 'IMPORT_TOO_MANY_QUESTIONS',

  // --- 作答 ---
  QUIZ_SESSION_NOT_FOUND: 'QUIZ_SESSION_NOT_FOUND',
  QUIZ_SESSION_ALREADY_SUBMITTED: 'QUIZ_SESSION_ALREADY_SUBMITTED',
  QUIZ_ANSWER_CHANGE_NOT_ALLOWED: 'QUIZ_ANSWER_CHANGE_NOT_ALLOWED',
  QUIZ_NO_QUESTIONS_MATCHED: 'QUIZ_NO_QUESTIONS_MATCHED',
  QUIZ_ANSWER_NOT_REVEALED_YET: 'QUIZ_ANSWER_NOT_REVEALED_YET',

  // --- 標籤 ---
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_DUPLICATED: 'TAG_NAME_DUPLICATED',
  TAG_PRIMARY_LIMIT_EXCEEDED: 'TAG_PRIMARY_LIMIT_EXCEEDED',
  TAG_SECONDARY_LIMIT_EXCEEDED: 'TAG_SECONDARY_LIMIT_EXCEEDED',
  TAG_MERGE_INVALID_TARGET: 'TAG_MERGE_INVALID_TARGET',

  // --- AI ---
  AI_JOB_NOT_FOUND: 'AI_JOB_NOT_FOUND',
  AI_JOB_ALREADY_RUNNING: 'AI_JOB_ALREADY_RUNNING',
  AI_JOB_NOT_CANCELLABLE: 'AI_JOB_NOT_CANCELLABLE',
  AI_PROVIDER_RATE_LIMITED: 'AI_PROVIDER_RATE_LIMITED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_OUTPUT_SCHEMA_INVALID: 'AI_OUTPUT_SCHEMA_INVALID',
  AI_OUTPUT_SEMANTIC_INVALID: 'AI_OUTPUT_SEMANTIC_INVALID',
  AI_CITATION_UNKNOWN_SOURCE: 'AI_CITATION_UNKNOWN_SOURCE',

  // --- 搜尋 / 擷取 ---
  SEARCH_PROVIDER_UNAVAILABLE: 'SEARCH_PROVIDER_UNAVAILABLE',
  URL_NOT_ALLOWED: 'URL_NOT_ALLOWED',

  // --- 答案衝突 ---
  ANSWER_CONFLICT_NOT_FOUND: 'ANSWER_CONFLICT_NOT_FOUND',
  ANSWER_CONFLICT_ALREADY_RESOLVED: 'ANSWER_CONFLICT_ALREADY_RESOLVED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const errorDetailSchema = z.object({
  /** 出錯欄位路徑，例如 questions[3].options[1].key */
  path: z.string().optional(),
  message: z.string(),
  /** 細部代碼，例如匯入驗證的 CORRECT_ANSWER_NOT_IN_OPTIONS */
  code: z.string().optional(),
});
export type ErrorDetail = z.infer<typeof errorDetailSchema>;

export const apiErrorSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    details: z.array(errorDetailSchema).optional(),
    /** 對應後端 log 的追蹤 ID，方便使用者回報問題 */
    requestId: z.string(),
    timestamp: z.string().datetime(),
  }),
});
export type ApiError = z.infer<typeof apiErrorSchema>;

/** 錯誤碼 -> HTTP 狀態碼；未列出者一律視為 500。 */
export const ERROR_STATUS_MAP: Partial<Record<ErrorCode, number>> = {
  VALIDATION_FAILED: 400,
  IMPORT_FILE_INVALID_JSON: 400,
  IMPORT_HAS_BLOCKING_ERRORS: 400,
  IMPORT_TOO_MANY_QUESTIONS: 400,
  AI_OUTPUT_SCHEMA_INVALID: 400,
  AI_OUTPUT_SEMANTIC_INVALID: 400,
  AI_CITATION_UNKNOWN_SOURCE: 400,
  URL_NOT_ALLOWED: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  REFRESH_TOKEN_INVALID: 401,
  FORBIDDEN: 403,
  CSRF_TOKEN_INVALID: 403,
  NOT_FOUND: 404,
  SUBJECT_NOT_FOUND: 404,
  CHAPTER_NOT_FOUND: 404,
  QUESTION_GROUP_NOT_FOUND: 404,
  QUESTION_NOT_FOUND: 404,
  IMPORT_BATCH_NOT_FOUND: 404,
  QUIZ_SESSION_NOT_FOUND: 404,
  TAG_NOT_FOUND: 404,
  AI_JOB_NOT_FOUND: 404,
  ANSWER_CONFLICT_NOT_FOUND: 404,
  CONFLICT: 409,
  CHAPTER_SUBJECT_MISMATCH: 409,
  QUESTION_IN_USE: 409,
  IMPORT_BATCH_NOT_COMMITTABLE: 409,
  QUIZ_SESSION_ALREADY_SUBMITTED: 409,
  QUIZ_ANSWER_CHANGE_NOT_ALLOWED: 409,
  QUIZ_ANSWER_NOT_REVEALED_YET: 409,
  TAG_NAME_DUPLICATED: 409,
  TAG_PRIMARY_LIMIT_EXCEEDED: 409,
  TAG_SECONDARY_LIMIT_EXCEEDED: 409,
  TAG_MERGE_INVALID_TARGET: 409,
  AI_JOB_ALREADY_RUNNING: 409,
  AI_JOB_NOT_CANCELLABLE: 409,
  ANSWER_CONFLICT_ALREADY_RESOLVED: 409,
  SETUP_ALREADY_COMPLETED: 410,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  QUIZ_NO_QUESTIONS_MATCHED: 422,
  RATE_LIMITED: 429,
  AI_PROVIDER_RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  DEPENDENCY_UNAVAILABLE: 503,
  AI_PROVIDER_UNAVAILABLE: 503,
  SEARCH_PROVIDER_UNAVAILABLE: 503,
};

export function httpStatusForErrorCode(code: ErrorCode): number {
  return ERROR_STATUS_MAP[code] ?? 500;
}
